const fs = require('fs');
const path = require('path');
const QRCode = require('qrcode');
const { Client, LocalAuth } = require('whatsapp-web.js');
const WhatsAppAdapter = require('./WhatsAppAdapter');
const config = require('../config/config');
const SanitizedLogger = require('../utils/SanitizedLogger');

const logger = new SanitizedLogger('WhatsAppWebAdapter');

class WhatsAppWebAdapter extends WhatsAppAdapter {
  constructor(options = {}) {
    super();
    this.options = options;
    this.client = null;
    this.tempDir = config.whatsapp.tempSessionDir;
    this.connectedAt = null;
    this.isConnecting = false;
    this.isDisconnecting = false;
    this.processedMsgIds = new Set();
    this._ensureTempDir();
  }

  _ensureTempDir() {
    if (!fs.existsSync(this.tempDir)) {
      try {
        fs.mkdirSync(this.tempDir, { recursive: true });
      } catch (err) {
        logger.error(`Failed to create temp session dir: ${err.message}`);
      }
    }
  }

  async connect() {
    if (this.isConnecting) {
      logger.warn('Connection already in progress. Ignoring duplicate request.');
      return;
    }
    this.isConnecting = true;

    if (this.client) {
      logger.warn('Client already exists. Disconnecting previous session first.');
      await this.disconnect();
    }

    this.connectedAt = null;
    this.emitConnectionChange(WhatsAppAdapter.STATUS.CONNECTING, { message: 'Iniciando navegador...' });

    try {
      this._ensureTempDir();

      // Safely clear any stale lockfile from an earlier terminated process
      try {
        const lockfilePath = path.join(this.tempDir, 'session-wa-assist-ephemeral', 'lockfile');
        if (fs.existsSync(lockfilePath)) {
          fs.unlinkSync(lockfilePath);
        }
      } catch (_) {}

      // Configure WhatsApp-Web.js client with isolated non-persistent temp storage
      this.client = new Client({
        authStrategy: new LocalAuth({
          dataPath: this.tempDir,
          clientId: 'wa-assist-ephemeral'
        }),
        puppeteer: {
          headless: config.whatsapp.puppeteer.headless,
          args: config.whatsapp.puppeteer.args
        }
      });

      this.client.on('qr', async (qr) => {
        logger.info('QR Code generated by WhatsApp Web.');
        try {
          this.qrCodeDataUrl = await QRCode.toDataURL(qr, {
            errorCorrectionLevel: 'M',
            margin: 2,
            width: 320
          });
          this.emitConnectionChange(WhatsAppAdapter.STATUS.WAITING_QR, { qr: this.qrCodeDataUrl });
        } catch (err) {
          logger.error(`Error generating QR Data URL: ${err.message}`);
        }
      });

      this.client.on('authenticated', () => {
        logger.info('WhatsApp authenticated. Loading session...');
        this.qrCodeDataUrl = null;
        this.emitConnectionChange(WhatsAppAdapter.STATUS.WAITING_AUTH, { message: 'Autenticado com sucesso. Sincronizando...' });
      });

      this.client.on('auth_failure', (msg) => {
        logger.warn('WhatsApp authentication failure');
        this.emitConnectionChange(WhatsAppAdapter.STATUS.SESSION_LOST, { error: 'Falha de autenticação' });
      });

      this.client.on('ready', () => {
        // Set connectedAt to current time
        this.connectedAt = Date.now() - 5000;
        logger.info('WhatsApp Web client is ready. Automation listener active.');
        this.qrCodeDataUrl = null;

        try {
          const info = this.client.info;
          this.clientInfo = {
            pushname: info?.pushname || 'Operador',
            phone: info?.wid?.user || '',
            platform: info?.platform || 'WhatsApp Web'
          };
        } catch {
          this.clientInfo = { pushname: 'Operador', phone: '', platform: 'WhatsApp Web' };
        }
        this.emitConnectionChange(WhatsAppAdapter.STATUS.CONNECTED, { clientInfo: this.clientInfo });
      });

      this.client.on('disconnected', async (reason) => {
        logger.warn(`WhatsApp client disconnected: ${reason}`);
        this.connectedAt = null;
        await this.disconnect();
      });

      // Unified Message Listener: handles both 'message' and 'message_create' with deduplication
      this.client.on('message', (msg) => this._handleMessage(msg));
      this.client.on('message_create', (msg) => this._handleMessage(msg));

      await this.client.initialize();
    } catch (err) {
      logger.error(`Error initializing WhatsApp Web client: ${err.message}`);
      this.emitConnectionChange(WhatsAppAdapter.STATUS.DISCONNECTED, { error: err.message });
      await this.disconnect();
      throw err;
    } finally {
      this.isConnecting = false;
    }
  }

  async _handleMessage(msg) {
    if (!msg || !msg.id) return;
    const msgId = msg.id._serialized || msg.id.id || String(msg.timestamp);

    // Idempotency: avoid processing duplicate emissions from 'message' and 'message_create'
    if (this.processedMsgIds.has(msgId)) {
      return;
    }
    this.processedMsgIds.add(msgId);
    if (this.processedMsgIds.size > 1000) {
      const first = this.processedMsgIds.values().next().value;
      this.processedMsgIds.delete(first);
    }

    // 1. If sent by the operator (myself)
    if (msg.fromMe) {
      if (msg.to && !msg.to.includes('@g.us') && !msg.to.includes('@broadcast')) {
        logger.info(`Operator sent message manually to ${msg.to}. Automatic handoff.`);
        const EventBus = require('../utils/EventBus');
        EventBus.publish(EventBus.EVENTS.HUMAN_HANDOFF, {
          contactId: msg.to,
          status: 'HANDOFF',
          info: 'Operador enviou mensagem manualmente pelo WhatsApp'
        });
      }
      return;
    }

    // 2. Incoming message from client
    logger.info(`Incoming message event received: from=${msg.from} type=${msg.type}`);

    // Discard status stories, broadcasts, channels/newsletters, groups
    if (msg.isStatus || !msg.from) return;
    if (msg.from === 'status@broadcast' || msg.from.includes('@broadcast') || msg.from.includes('@g.us') || msg.from.includes('@newsletter')) {
      return;
    }

    // Must have non-empty text content
    if (!msg.body || !msg.body.trim()) {
      return;
    }

    // Check message timestamp: do not process messages sent earlier than 2 minutes before ready
    const msgTime = msg.timestamp ? msg.timestamp * 1000 : Date.now();
    if (this.connectedAt && msgTime < (this.connectedAt - 120000)) {
      logger.info(`Ignoring older historical message: ${new Date(msgTime).toISOString()}`);
      return;
    }

    // Contact JID resolution (normalize to phone@c.us if possible)
    let contactJid = msg.from;
    let senderName = msg._data?.notifyName || '';
    try {
      const contact = await msg.getContact();
      if (contact) {
        senderName = contact.pushname || contact.name || senderName;
        if (contact.id && contact.id._serialized && contact.id._serialized.endsWith('@c.us')) {
          contactJid = contact.id._serialized;
        }
      }
    } catch {
      // ignore
    }

    logger.info(`Inbound customer message eligible for automation: from=${contactJid} name=${senderName}`);

    this.emitIncomingMessage({
      id: msg.id?.id || String(Date.now()),
      from: contactJid,
      fromName: senderName,
      body: msg.body.trim(),
      timestamp: msgTime,
      isGroup: false
    });
  }

  async disconnect() {
    if (this.isDisconnecting) return;
    this.isDisconnecting = true;
    logger.info('Disconnecting WhatsApp Web client...');
    this.connectedAt = null;

    if (this.client) {
      const c = this.client;
      this.client = null;
      try {
        if (c.pupBrowser) {
          try {
            const proc = c.pupBrowser.process();
            await c.pupBrowser.close().catch(() => {});
            if (proc && !proc.killed) {
              proc.kill('SIGKILL');
            }
          } catch (_) {}
        }
        await c.destroy().catch((err) => {
          logger.warn(`Ignored error during client.destroy: ${err.message}`);
        });
      } catch (err) {
        logger.warn(`Error destroying client: ${err.message}`);
      }
    }

    await new Promise(r => setTimeout(r, 400));

    try {
      const lockfilePath = path.join(this.tempDir, 'session-wa-assist-ephemeral', 'lockfile');
      if (fs.existsSync(lockfilePath)) {
        fs.unlinkSync(lockfilePath);
      }
    } catch (_) {}

    this.qrCodeDataUrl = null;
    this.clientInfo = null;
    this.emitConnectionChange(WhatsAppAdapter.STATUS.DISCONNECTED);
    this.isDisconnecting = false;
  }

  async sendMessage(to, text) {
    if (!this.client || this.status !== WhatsAppAdapter.STATUS.CONNECTED) {
      throw new Error('WhatsApp client is not connected.');
    }

    try {
      // Normalize recipient JID: if only phone number passed, append @c.us
      let recipient = to;
      if (!recipient.includes('@')) {
        recipient = `${recipient.replace(/\D/g, '')}@c.us`;
      }

      const res = await this.client.sendMessage(recipient, text);
      return { success: true, id: res?.id?.id };
    } catch (err) {
      logger.error(`Failed to send message: ${err.message}`);
      return { success: false, error: err.message };
    }
  }

  async getProfilePicUrl(contactId) {
    if (!this.client || this.status !== WhatsAppAdapter.STATUS.CONNECTED) {
      return null;
    }
    try {
      let jid = contactId;
      if (!jid.includes('@')) {
        jid = `${jid.replace(/\D/g, '')}@c.us`;
      }
      const picUrl = await this.client.getProfilePicUrl(jid);
      return picUrl || null;
    } catch (_) {
      return null;
    }
  }

  async getChatMessages(contactId, limit = 50) {
    if (!this.client || this.status !== WhatsAppAdapter.STATUS.CONNECTED) {
      return [];
    }
    try {
      let jid = contactId;
      if (!jid.includes('@')) {
        jid = `${jid.replace(/\D/g, '')}@c.us`;
      }
      const chat = await this.client.getChatById(jid);
      if (!chat) return [];
      const msgs = await chat.fetchMessages({ limit });
      return msgs.map(m => ({
        id: m.id?._serialized || m.id?.id || String(m.timestamp),
        body: m.body || '',
        fromMe: Boolean(m.fromMe),
        timestamp: (m.timestamp || Date.now() / 1000) * 1000,
        type: m.type || 'chat'
      }));
    } catch (err) {
      logger.warn(`Could not fetch messages for ${contactId}: ${err.message}`);
      return [];
    }
  }
}

module.exports = WhatsAppWebAdapter;
